### ISSUE TITLE
Create new build and sync python3-requirements on new EDMC release

### ISSUE THREAD

**Issue by dvdmuckle** [flathub/io.edcd.EDMarketConnector#66]
Manually syncing the python3-requirements is a bit of a chore (since we don't want to stay on the leading edge with dependencies in the case of some incompatibility), but it's something that needs to be done manually any time there's a new EDMC release. We should investigate how to automatically sync the `python3-requirements.yaml` to EDMC's `requirements.txt` automatically any time there's a new EDMC release.

**Comment by imide** [comment]
sorry for sorta necroposting, but here is how I did something similar but should be easily converted to EDMC.
source is here: https://github.com/flathub/app.legcord.Legcord/blob/master/.github/workflows/auto-update.yaml

```yaml
name: Auto update

on:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Setup environment variables
        run: |
          echo "FLATPAK_BUILDER_TOOLS_DIR=/tmp/flatpak-builder-tools" >> $GITHUB_ENV
          APP_URL="$(yq '.modules[0].sources[] | select(.url | test("archive/v.*\\.tar\\.gz")) | .url' app.legcord.Legcord.yaml)"
          APP_VERSION=$(echo "$APP_URL" | sed -E 's|.*/v([0-9.]+)\.tar\.gz|\1|')
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Setup flatpak-builder-tools
        run: |
          git clone --depth=1 https://github.com/flatpak/flatpak-builder-tools ${FLATPAK_BUILDER_TOOLS_DIR}
          pip install --user pipx && pipx install ${FLATPAK_BUILDER_TOOLS_DIR}/node
          pip install --user toml aiohttp

      - name: Update Node.js generated sources
        run: |
          git clone https://github.com/Legcord/Legcord.git --depth=1 --branch=v${APP_VERSION} /tmp/app

          flatpak-node-generator pnpm /tmp/app/pnpm-lock.yaml --node-sdk-extension org.freedesktop.Sdk.Extension.node26 --electron-node-headers --pnpm-store-version v11 -o generated-sources.json

      # This is disabled until the next release of legcord. 
      # - name: Fetch generated-sources.json from release
      #   uses: robinraju/release-downloader@v1
      #   with:
      #       repository: 'Legcord/Legcord'
      #       tag: v${{ env.APP_VERSION }}
      #       fileName: 'generated-sources.json'

      - name: Commit updates
        run: |
          set -e

          [[ ! $(git status --porcelain) ]] && exit 0

          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "Workflow trigger"

          git add generated-sources.json
          git commit -m 'Update generated sources'

          git push https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}
```
